CREATE TABLE Service (_id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT, Information TEXT, Website TEXT);
CREATE TABLE Schedule (_id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT, Description TEXT, Event TEXT);
CREATE TABLE Contact (_id INTEGER PRIMARY KEY AUTOINCREMENT, Contact TEXT, Position TEXT, Phone TEXT, Cell TEXT, Mail TEXT);
INSERT INTO Service (Name, Information, Website) values ('Enfermeria','Ofrece: -Toma de signos vitales -Curaciones y procedimientos especiales -Nebulizaciones -Atencion de emergencias -Aplicacion de inyectables', 'http://www.tec.ac.cr/sitios/Vicerrectoria/viesa/tss/Biblioteca_Paginas/atencion_directa.aspx');
INSERT INTO Service (Name, Information, Website) values ('Medicina','Ofrece: -Atencion medica -Cirugias menores -Realizacion de electrocardiogramas -Control de enfermedades cronicas -Referencia a especialistas', 'http://www.tec.ac.cr/sitios/Vicerrectoria/viesa/tss/Biblioteca_Paginas/atencion_directa.aspx');
INSERT INTO Service (Name, Information, Website) values ('Odontologia','Esclusivo para la poblacion estudiantil. Ofrece: -Examenes clinicos -Radiografias -Operatoria dental -Extracciones -Cirugia oral menor -Tratamientos de nervio -Educacion sobre salud oral -Limpieza bucal', 'http://www.tec.ac.cr/sitios/Vicerrectoria/viesa/tss/Biblioteca_Paginas/atencion_directa.aspx');
INSERT INTO Service (Name, Information, Website) values ('Nutricion','Ofrece: -Valoracion de usuarios -Elaboracion de planes alimenticios -Consulta de seguimiento -Asesorias nutricionales', 'http://www.tec.ac.cr/sitios/Vicerrectoria/viesa/tss/Biblioteca_Paginas/atencion_directa.aspx');
INSERT INTO Service (Name, Information, Website) values ('Psicologia Clinica','Ofrece: -Psicodiagnostico -Psicoterapia -Intervencion en crisis', 'http://www.tec.ac.cr/sitios/Vicerrectoria/viesa/tss/Biblioteca_Paginas/atencion_directa.aspx');
INSERT INTO Service (Name, Information, Website) values ('Programa de Alcoholismo y Drogodependencia','El programa atiende a aquellas personas que tengan problemas de uso, abuso o adiccion a sustancias o actividades', 'http://www.tec.ac.cr/sitios/Vicerrectoria/viesa/tss/Biblioteca_Paginas/atencion_directa.aspx');
INSERT INTO Service (Name, Information, Website) values ('Programa de Salud Sexual y Reproductiva','Ofrece: -Consulta prenatal - Consulta de planificacion familiar y salud sexual - Toma de citologias o papanicolau femeninos y masculinos - Curso de preparacion para el parto', 'http://www.tec.ac.cr/sitios/Vicerrectoria/viesa/tss/Biblioteca_Paginas/atencion_directa.aspx');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Ana Iris Mata Coto', 'Asistente de Dentista','2550-9178', '--', 'anmata@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Bettzy Rojas Molina', 'Psicologa','2550-9175', '--', 'brojas@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Diana Segura Soto', 'Directora','2550-2276', '--', 'disegura@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Elias Meneses Rimola', 'Odontologo','2550-9178', '--', 'emeneses@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Gabriela Montero Rodriguez', 'Nutricionista','--', '--', 'gmontero@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('German Araya Jimenez', 'Doctor','2550-9177', '--', 'garaya@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Jesus Artavia Gutierrez', 'Paramedico','2550-9191', '--', 'jeartavia@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Jose Luis Valverde Araya', 'Doctor','2550-9292', '--', 'jlvalverde@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Lilliana Harley Jimenez', 'Doctora','2550-9174', '--', 'lharley@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Margarita Hernandez Jimenez', 'Doctora','2550-9179', '--', 'marghernandez@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Maria Gabriela Castro Chacon', 'Odontologa','2550-9178', '--', 'mcastro@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Maricela Meono Marti', 'Enfermera','2550-9176', '--', 'mmeono@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Milagro Bonilla Moya', 'Psicologa','2550-9181', '--', 'mibonilla@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Nuria Solano Ortega', 'Asistente de Dentista','2550-9178', '--', 'nsolano@itcr.ac.cr');
INSERT INTO Contact (Contact, Position, Phone, Cell, Mail) values ('Rita Ramirez Brenes', 'Secretaria','2550-9180', '--', 'rramirez@itcr.ac.cr');

